# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_bon.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Bon_TableWidget(object):
    def setupUi(self, mainWidget,no_rows):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(1303, 733)
        font = QtGui.QFont()
        font.setPointSize(10)
        mainWidget.setFont(font)
        mainWidget.setAutoFillBackground(False)
        self.bon_table = QtWidgets.QTableWidget(mainWidget)
        self.bon_table.setGeometry(QtCore.QRect(180, 40, 931, 591))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bon_table.setFont(font)
        self.bon_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bon_table.setRowCount(no_rows)
        self.bon_table.setColumnCount(7)
        self.bon_table.setObjectName("bon_table")
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.bon_table.setHorizontalHeaderItem(6, item)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "main"))
        item = self.bon_table.horizontalHeaderItem(0)
        item.setText(_translate("mainWidget", "ID_client"))
        item = self.bon_table.horizontalHeaderItem(1)
        item.setText(_translate("mainWidget", "ID_comanda"))
        item = self.bon_table.horizontalHeaderItem(2)
        item.setText(_translate("mainWidget", "ID_pizza"))
        item = self.bon_table.horizontalHeaderItem(3)
        item.setText(_translate("mainWidget", "Pret"))
        item = self.bon_table.horizontalHeaderItem(4)
        item.setText(_translate("mainWidget", "Cantitate"))
        item = self.bon_table.horizontalHeaderItem(5)
        item.setText(_translate("mainWidget", "Pret/tip pizza"))
        item = self.bon_table.horizontalHeaderItem(6)
        item.setText(_translate("mainWidget", "Cost_total"))

    def show_table(self):
        self.bon_table.show()

    def get_table(self):
        return self.bon_table

    def hide(self):
        self.bon_table.hide()

    def set_no_rows(self,rows):
        try:
            #print("set no rows bon")
            self.bon_table.setRowCount(rows)
        except Exception as err:
            print(err)
